import { StyleSheet } from 'react-native'
import { colors } from '../../../theme/tokens'
import { CHECKIN_MODAL_CONSTANTS } from './CheckInModal.constants'

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    keyboardView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    modalWrapper: {
        width: '100%',
        maxWidth: 400,
        position: 'relative',
    },
    shadowLayer: {
        position: 'absolute',
        top: 6,
        left: 6,
        right: -6,
        bottom: -6,
        backgroundColor: colors.brownDark,
        borderRadius: 20,
        width: '100%',
        height: '100%',
    },
    modalContent: {
        backgroundColor: colors.cream,
        borderRadius: 20,
        borderWidth: 3,
        borderColor: colors.brown,
        padding: 24,
    },
    title: {
        fontSize: 22,
        fontWeight: '700',
        color: colors.brown,
        textAlign: 'center',
        marginBottom: 20,
        fontFamily: CHECKIN_MODAL_CONSTANTS.FONTS.BOLD,
    },
    inputContainer: {
        backgroundColor: colors.creamDark,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: colors.brown,
        padding: 16,
        marginBottom: 16,
    },
    textInput: {
        fontFamily: CHECKIN_MODAL_CONSTANTS.FONTS.REGULAR,
        fontSize: 16,
        color: colors.charcoal,
        minHeight: 80,
        textAlignVertical: 'top',
    },
    label: {
        fontSize: 14,
        color: colors.gray,
        marginBottom: 8,
        fontFamily: CHECKIN_MODAL_CONSTANTS.FONTS.REGULAR,
    },
    dropdownTrigger: {
        backgroundColor: colors.creamDark,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: colors.brown,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    dropdownOptions: {
        position: 'absolute',
        top: '100%',
        left: 0,
        right: 0,
        backgroundColor: colors.cream,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: colors.brown,
        marginTop: 4,
        overflow: 'hidden',
        shadowColor: colors.brownDark,
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 0,
        elevation: 5,
        zIndex: 1000,
    },
    optionItem: {
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    dot: {
        width: 12,
        height: 12,
        borderRadius: 6,
    },
    buttonContainer: {
        flex: 1,
        position: 'relative',
    },
    buttonShadow: {
        position: 'absolute',
        top: 3,
        left: 3,
        right: -3,
        bottom: -3,
        borderRadius: 16,
        width: '100%',
        height: '100%',
    },
    buttonBase: {
        borderRadius: 16,
        borderWidth: 2,
        paddingVertical: 14,
        alignItems: 'center',
    },
    buttonText: {
        fontSize: 16,
        fontWeight: '600',
        fontFamily: CHECKIN_MODAL_CONSTANTS.FONTS.SEMIBOLD,
    }
})
