import { StyleSheet } from 'react-native'
import { colors } from '../../../theme/tokens'
import { HOME_SCREEN_CONSTANTS } from './HomeScreen.constants'

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.cream,
    },
    header: {
        paddingTop: 60,
        paddingBottom: 20,
        alignItems: 'center',
    },
    headerText: {
        fontSize: 32,
        fontWeight: '800',
        color: colors.brown,
        fontFamily: HOME_SCREEN_CONSTANTS.FONTS.BOLD,
        textTransform: 'uppercase',
        letterSpacing: 3,
        textShadowColor: 'rgba(0,0,0,0.15)',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 0,
    },
    contentArea: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 24,
        marginTop: -40,
    },
    glowEffect: {
        position: 'absolute',
        width: HOME_SCREEN_CONSTANTS.GLOW_SIZE,
        height: HOME_SCREEN_CONSTANTS.GLOW_SIZE,
        borderRadius: HOME_SCREEN_CONSTANTS.GLOW_SIZE / 2,
        backgroundColor: 'rgba(255, 230, 150, 0.5)',
        shadowColor: '#FFE699',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 30,
    },
    outerRing: {
        width: HOME_SCREEN_CONSTANTS.OUTER_RING_SIZE,
        height: HOME_SCREEN_CONSTANTS.OUTER_RING_SIZE,
        borderRadius: HOME_SCREEN_CONSTANTS.OUTER_RING_SIZE / 2,
        borderWidth: 3,
        borderColor: colors.brown,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
        shadowColor: colors.brownDark,
        shadowOffset: { width: 4, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 0,
        elevation: 4,
    },
    statusText: {
        fontSize: 24,
        fontWeight: '700',
        color: colors.brown,
        textAlign: 'center',
        marginTop: 32,
        fontFamily: HOME_SCREEN_CONSTANTS.FONTS.BOLD,
    },
    bottomSection: {
        paddingHorizontal: 24,
        paddingBottom: 32,
    },
    shadowCardContainer: {
        position: 'relative',
    },
    shadowCardShadow: {
        position: 'absolute',
        top: 4,
        left: 4,
        right: -4,
        bottom: -4,
        backgroundColor: colors.brownDark,
        borderRadius: 16,
        width: '100%',
        height: '100%',
    },
    shadowCardMain: {
        backgroundColor: colors.creamDark,
        borderRadius: 16,
        borderWidth: 3,
        borderColor: colors.brown,
        paddingHorizontal: 16,
        paddingVertical: 14,
    },
    badge: {
        width: 44,
        height: 44,
        backgroundColor: colors.cream,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: colors.brown,
        alignItems: 'center',
        justifyContent: 'center',
    },
    badgeText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.terracotta,
        fontFamily: HOME_SCREEN_CONSTANTS.FONTS.BOLD,
    },
    counterLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: colors.brown,
        fontFamily: HOME_SCREEN_CONSTANTS.FONTS.SEMIBOLD,
    },
    resetLabel: {
        fontSize: 12,
        color: colors.gray,
        fontFamily: HOME_SCREEN_CONSTANTS.FONTS.REGULAR,
    },
    pillButtonWrapper: {
        position: 'relative',
        marginBottom: 20,
    },
    pillButtonShadow: {
        position: 'absolute',
        top: 4,
        left: 4,
        right: -4,
        bottom: -4,
        backgroundColor: colors.brownDark,
        borderRadius: 20,
        width: '100%',
        height: '100%',
    },
    pillButtonContent: {
        borderColor: colors.brownDark,
        borderWidth: 3,
        borderRadius: 20,
        paddingHorizontal: 24,
        paddingVertical: 20,
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
    },
    pillButtonText: {
        fontSize: 18,
        fontWeight: '700',
        flex: 1,
        fontFamily: HOME_SCREEN_CONSTANTS.FONTS.BOLD,
    },
    pillButtonIconWrapper: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255,255,255,0.25)',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 24,
    },
    circularProgressContainer: {
        borderWidth: 3,
        borderColor: 'rgba(0,0,0,0.1)',
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
        overflow: 'hidden',
    },
    circularProgressFill: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: colors.sage,
        opacity: 0.5,
    },
    circularProgressBorderOverlay: {
        position: 'absolute',
        top: -3,
        left: -3,
        right: -3,
        bottom: -3,
        borderWidth: 3,
        borderColor: colors.brown,
        opacity: 0.2
    },
    circularProgressActiveBorder: {
        position: 'absolute',
        top: -3,
        left: -3,
        right: -3,
        bottom: -3,
        borderWidth: 3,
        borderColor: colors.sage,
    }
})
